### ISSUE TITLE
libusb couldn't open USB device /dev/bus/usb/001/066: Permission denied

### ISSUE THREAD

**Issue by nixtux** [HughPH/SteelSeriesControl#2]
./SteelSeriesControl LED logo Steady Red Red 200
libusb: error [_get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/066: Permission denied
libusb: error [_get_usbfs_fd] libusb requires write access to USB device nodes.
Could not open device

**Comment by nixtux** [comment]
Added a basic udev to try and help (SUBSYSTEM=="usb", ATTRS{idVendor}=="1038", ATTRS{idProduct}=="1700", MODE="0666")

but now i get this error
./SteelSeriesControl Tactile 50
Could not detach kernel driver on interface 0
Could not attach kernel driver on interface 0
[1]    26642 segmentation fault (core dumped)  ./SteelSeriesControl Tactile 50

**Comment by Kira-PH** [comment]
Sorry, I have no idea what could be going on. It looks like a more generic issue related to libusb, others have experienced the same issue with other codebases.

For example: https://github.com/openhab/openhab-docker/issues/176
